---
title: "Script para lista 2"
output:
  pdf_document: default
  html_document: default
date: "2025-09-18"
---

# Script para lista - Módulo 2

## 1) 

```{r}
lst <- list(a = 1:3, b = list(c = 10, d = 20:21))
lst[[2]][[2]]
lst[["b"]][["d"]]
View(lst)
lst$b
```

## 2)

```{r}
x <- c(2, 5, 0, -3)

x^2 - 2 * x + 1
x^2 - 2*x + 1


```

## 3)

```{r}
ls(envir = ambiente, all.names = TRUE)
```


## 4)

```{r}
v <- c("a", "b", "c")
factor(v, levels = c("c", "b", "a"), ordered = TRUE)
```

## 5)

```{r}
# matriz
```

## 6)

```{r}
utils:::format.object_size(sapply(ls(), function(x) object.size(get(x))))


```

## 7)

```{r}

rep(1:4, times=5)
```

## 8)

```{r}
df <- data.frame(a = 1:4, b = c("x", "y", "z", "w"))
df[df$a>2,]
```

## 9)

```{r}
library()
```

## 10)

```{r}
# para atach a incorreta é

#Variáveis com mesmo nome no Global Environment têm precedência sobre as do data frame anexado.
```

## 11)

```{r}
# typeof() retorna o tipo interno; class() retorna a classe S3 ou S4.
```

## 12)

```{r}
# descrição de um fator

# Um vetor com níveis que representam categorias.


```

## 13)

```{r}
rep(c(10,20,30), times=2)

```

## 14)

```{r}
df <- data.frame(a = 1:5, b = letters[1:5], stringsAsFactors = FALSE)

df[-3, ]


```

## 15)

```{r}
mtcars[mtcars$mpg > 20 & mtcars$mpg < 25, ]
```

## 17)

```{r}
seq(100, 10, by = -10)
```

## 18)

```{r}
update.packages(ask = FALSE)
```

## 20)

```{r}
m <- matrix(1:9, 3, 3)
print(m)
m[2,3]
```

## 21)
sobre data frames

```{r}
# Cada coluna é um vetor; colunas podem ter tipos diferentes.
```

## 22)

```{r}
x <- c(1,2,3,4)
is.atomic(x)
is.list(x)
```

## 23)



## 24)

```{r}
df <- data.frame(a = 1:3, b = c("x", "y", "z"))
s <- df[,1]
View(s)
```

## 25) 

```{r}

```


## 27)

```{r}

iris[seq(10, 100, 5), ]
```

## 30)

```{r}
rep(7, times=10)


```

## 31) 

```{r}
seq(1,9,length.out=5)
seq(1,9,by=2)
c(1,3,5,7,9)
# 1:9[seq(1,9,by=2)]

```

## 33) e 34)

```{r}
rep(1:3, each = 2)
rep(1:3, times = 3)
```

## 38)

```{r}
View(airquality)
airquality[!is.na(airquality$Ozone), ]
```

## 39)

```{r}
arr <- array(1:24, dim = c(2,3,4))
View(arr)
arr[1,,3]

```

## 42) 

```{r}
lst <- list(x = 1:3, y = list(a = 10, b = 20))


lst$y[[2]]
is.numeric(lst$y[[2]])

```

## 43) 

```{r}
m <- matrix(1:6, nrow = 2)
is.matrix(m)
```

## 44)

```{r}
df <- data.frame(x = 1:3, y = letters[1:3])

df$z <- list(10,20,30)
is.list(df$z)

```

## 47)

```{r}
 v <- 1:10
v>5
subset(v, v > 5)
```

