---
title: "Trabalho Final - Elementos de Prog"
date: "`r format(Sys.time(), '%d / %m / %y')`"
author: 
  - "Antonio Paulo Steffen Neto"
  - "Ingrid"
  - "Jhullya da Rosa Shalders"
  - "Pedro"
output: html_document
bibliography: citations.bib 
---

## Introdução {#sec-01}

Este trabalho se propõe a ser a parte de conclusão do Módulo 5 da discilpina CE302 - Elementos de Programação para Estatística. Para tal, ele consiste em uma análise de um conjunto de dados disponibilizado pelos professores responsáveis e subsequente desenvolvimento de um aplicativo em Shiny para visualização dos resultados encontrados. Assim, este trabalho apresenta a parte técnica e teórica do que foi realizado pelo grupo. A parte da apresentação em um aplicativo em Shiny, por outro lado, será feita por meio de um vídeo de apresentação do grupo. Nesta introdução apresentamos, então, o conjunto de dados escolhido pelo grupo e, também, como a parte escrita do trabalho está estruturada.
Sobre a escolha do conjuntos de dados disponibilizados, o grupo optou pelo conjunto da dados chamado *Allrecipes*. Neste constam dados retirados do site [Allrecipes](https://www.allrecipes.com) sobre receitas, seus países de origem e autores, informações nutricionais, tempo de preparo, avaliações e vezes em que foram reproduzidas. Assim sendo, todas as informações a serem referenciadas no texto têm como fonte @noauthor_allrecipes_nodate.
Como definido pelas instruções dadas pela proposta de trabalho, a formatação deste segue a ordem: Introdução; Materiais e Métodos; Resultados e Discussão; Conclusão e Referências. Muitas das partes integrantes da ordem originalmente indicada, naturalmente, apresentam suas próprias subseções, assim sendo, esta **Introdução** conta com duas subseções: Contextualização e Definição do Problema e Objetivos da Análise. A parte de Materiais e Métodos, por sua vez, tem como sbdivisões: Descrição do Conjunto de Dados, Dicionário de Variáveis, Tratamento de Dados e Técnicas Estatísticas e Computacionais. Na sequência, são apresentados os Resultados e Discussão, divididos de acordo com temas de análise, com suas respectivas análises e interpretações como será, posteriormente, fácil de analisar com o aplicativo Shiny feito em conjunto com esta parte escrita. Por fim, a Conclusão e as Referências Bibliográficas não apresentam quaisquer divisões.

### Contextualização e Definição do Problema

A alimentação é a base de toda a cultura humana, o momento de comunhão em diferentes culturas e religiões. Isso estende-se desde o cômodo onde as pessoas se alimentam até a como grandes festividades por todo o globo costumam ter alguma refeição como parte central das celebrações. Mais recentemente, o destaque adquirido por grandes chefes de cosinha e por produtos culturais como reality show e séries sobre culinária são sintomas deste fenômeno. 
Mais recentemente, contudo, a relação das pessoas com a comida foi muito modificada e tornada mais complexa. Em tempos de internet, fast food e fácil acesso a ingredientes de todo o mundo, sites como o *Allrecipes* se tornaram um meio impressindível de compartilhamento de hábitos alimentares e, para pesquisadores, uma fonte preciosa de dados para entender como as pessoas se alimentam. Mas sobre o que se trata o site em questão? O *Allrecipes* consiste em um site de compartilhamento de receitas. Nele, usuários de todo o mundo podem postar suas receitas para que outras pessoas possam prová-las, acompanhar as avaliações dos outros usuários e, também, acessar receitas de outros usuários, igualmente prová-las e avaliá-las. O site *Allrecipes*, portanto, e já olhando para os dados de interesse na presente análise, nos traz dados a respeito da origem das receitas e por quem foram postadas. Além disso, também inclui as informações acerca de tempos de preparo e, também, de questões nutricionais. 
A análise de dados não estruturados provenientes da plataforma online *Allrecipes* insere-se na emergente área dGastronomia Computacional, que tem por objetivo o emprego de técnicas *data-driven* para o estudo e a análise de comidas. Esse campo busca quantificar e modelar fenômenos culinários e de consumo alimentar. Neste contexto, o volume e a variedade dos dados de receitas (incluindo as avaliações, informações nutricionais e origem geográfica) constituem um conjunto de dados de nicho, que seria ideal para a aplicação de métodos de aprendizado de máquina e modelagem estatística, caso os autores deste trabalho estivessem mais adiante no curso de Estatística.


### Objetivos da Análise

Dado o conjunto de dados escolhido, portanto, é possível uma análise que cubra de maneira completa todas as variáveis a disposição, ainda que, para tal, seja necessário um trabalho de grande escopo que cubra diversas frentes. Assim, abrem-se diversas direções de investigação. Tanto as informações nutricionais quanto as informações acerca dos ingredientes podem ser entrelaçadas e apresentam grande complexidade. Além destas, tem
O panorama geral da análise será análisado em conjunto com as informações nutricionais gerais; além deles, os tempos de preparo; as quantidades de ingredientes; e, por fim, um olhar tendo como base os países de origem de cada receita.

O objetivo principal da análise, portanto, será o de entender quais as dinâmicas por trás da popularidade de receitas publicadas online. Assim sendo, a análise sserá conduzida em partes e em três diferentes frentes: a do perfil nutricional, que investiga as relações entre variáveis nutricionais contínuas e a variável de resposta popularidade (medida por avaliações médias e totais e reproduções das receitas; a complexidade dos preparos, isto é, o impacto do tempo e das quantidades de ingredientes na impacto causado pelas receitas; e a da origem geocultural das receitas, analisando a distribuição de popularidades e perfis nutricionais dentro do conjunto de dados. Em cada uma das frentes serão analisadas relações com as avaliações médias e com a quantidade de reproduções das receitas.
Com relação ao perfil nutricional das receitas, serão analisados os perfis das receitas, buscando relações entre seus componentes e também os perfis de composições de ingredientes presentes. 

## Materiais e Métodos {#sec-02}

Teremos como principal material de apoio, suplemntar aos materiais da disciplina, o livro *R for data science: import, tidy, transform, visualize, and model data*, de autoria de @wickham_r_2017. Também serão utilizados para análise de observações o que é desenvolvido por @agresti_introduction_2019.
Além de ambos, também serão utilizados materiais de @trattner_estimating_2017 e @hussain_innovative_2025, que já desenvolveram análises semelhantes à que este trabalho se propõe. Além disso, também será utilizada @silva_da_costa_percepcao_2021

### Descrição do Conjunto de Dados 

Para fazer a descrição dos conjuntos de dados fornecidos, começamos utilizando a função `str()` para vermos as descrições estruturais de ambos os conjuntos. 

```{r}
str(all_recipes)
str(cuisines)
```

Isto feito, podemos dizer que o primeiro conjunto, o maior, chamado `all_recipes`, é constituído de 14.426 observações e 16 variáveis; o segundo, `cuisines`, 2.218 e 17 variáveis. O segundo conjunto tem, portanto, uma variável a mais, esta sendo a variável *country*, uma variável de caracteres que descreve o país de origem da receita. Nas outras variáveis, presentes em ambos os conjuntos de dados, há informações que descrevem as receitas postadas no site, trazendo informações dos autores, url's das receitas, ingredientes e informações nutricionais, tempos de preparo, cozimento e total, avaliações e vezes reproduzidas. Três das variáveis são do tipo caracteres, um do tipo data, e o restante valores numéricos. 
As observações vêm em uma ordem padrão de índice (definida pelo fornecedor), mas podem ser facilmente classificadas (reordenadas) de acordo com as variáveis disponíveis, como, por exemplo, ordem crescente ou decrescente de calorias, classificação média, ou tempo de preparo, etc. 

### Dicionário de Variáveis

Abaixo, temos um dicionário das variáveis existentes em ambos os conjuntos de dados:

1. `all_recipes`:

| Variável | Tipo de Dado | Descrição Completa |
|----------|--------------|--------------------|
| recipe_id | Numérico/Inteiro | Identificador único. Chave para fusão de dados. |
| author | Caractere/Fator | Nome do usuário que postou a receita. |
| recipe_name | Caractere | Nome da receita. |
| url | Caractere | Link da receita. |
| ingredients | Caractere | Base para contagem de ingredientes. |
| prep_time_minutes | Numérico | Tempo de preparo (minutos). |
| cook_time_minutes | Numérico | Tempo de cozimento (minutos). |
| total_time_minutes | Numérico | Tempo total (preparo + cozimento). Variável chave para Complexidade. |
| servings | Numérico | Número de porções que a receita produz. |
| calories | Numérico | Conteúdo energético (Kcal). Variável chave Nutricional. |
| fat | Numérico | Quantidade de gordura (g). |
| protein | Numérico | Quantidade de proteína (g). |
| sodium | Numérico | Quantidade de sódio (mg). |
| rating | Numérico | Avaliação média (1-5). Métrica de popularidade. |
| n_ratings | Numérico/Inteiro | Número de avaliações recebidas. |
| n_reproducidas | Numérico/Contagem | Principal variável de resposta (popularidade). |
| date_published | Data | Data em que a receita foi publicada no site. |

2. `cuisines`:



| Variável | Tipo de Dado | Descrição Completa e Relevância |
| ---------|------------------------- | ---------------- | ---------------------------------------------------------------------------------------------------------------- |
| recipe_id | Numérico/Inteiro | Identificador único. Chave para fusão de dados. |
| author | Caractere/Fator | Nome do usuário. |
| recipe_name | Caractere | Nome da receita. |
| url | Caractere | Link da receita. |
| ingredients | Caractere | Usado para derivar a contagem de ingredientes. |
| prep_time_minutes | Numérico | Tempo de preparo (minutos). |
| cook_time_minutes | Numérico | Tempo de cozimento (minutos). |
| total_time_minutes | Numérico | Tempo total (preparo + cozimento). |
| servings | Numérico | Número de porções. |
| calories | Numérico | Conteúdo energético (Kcal). |
| fat | Numérico | Quantidade de gordura (g). |
| protein | Numérico | Quantidade de proteína (g). |
| sodium | Numérico | Quantidade de sódio (mg). |
| rating | Numérico | Avaliação média (1-5). Métrica de popularidade. |
| n_ratings | Numérico/Inteiro | Número de avaliações recebidas. |
| n_reproducidas | Numérico/Contagem | **Principal variável de resposta (popularidade)**. |
| date_published | Data | Data de publicação. |
| country | Caractere/Fator | **País de origem.** Variável chave para análise geocultural (vem do `cuisines`). |

### Tratamento dos Dados 

1. Fusão de Conjuntos de Dados: Inicialmente, o dataset principal (all_recipes) foi unido ao dataset auxiliar (cuisines) utilizando-se a variável de chave primária (recipe_id ou equivalente), resultando em um único data frame analítico.

2. Tratamento de Valores Faltantes (NA): Verificou-se a presença de valores NA (Not Available) nas variáveis nutricionais. Foi adotada a estratégia de imputação por mediana para os NAs em variáveis contínuas, como calorias, onde a ausência de informação era considerada Missing At Random (MAR), para maximizar o número de observações úteis. Para a variável country, os NAs foram categorizados como "Não Especificado".

3.  Padronização e Normalização: Variáveis com alta variabilidade, como reproduções, foram consideradas para transformação logarítmica $(\log(X+1))$ para aproximar suas distribuições de uma normalidade e mitigar a influência de outliers extremos no ajuste dos modelos de regressão.

4. Codificação de Variáveis Categóricas: A variável country foi convertida para o tipo fator (factor) para uso em modelos estatísticos, sendo implementado o esquema de codificação dummy (variáveis binárias) para as análises de regressão.

### Técnicas Estatísticas e Computacionais

As técnicas estatísticas empregadas no trabalho seguem, de maneira geral, 

## Resultados e discussão {#sec-03}

### Análises e Interpretações

## Conclusão {#sec-04}

## Referências Bibliográficas {#sec-05}



